<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ed</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Eido</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\{(=*)\{</string>
			<key>end</key>
			<string>\}\1\}</string>
			<key>name</key>
			<string>string.unquoted.raw.eido</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.string.unquoted.raw.content.eido</string>
					<key>match</key>
					<string>.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.eido</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.eido</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.group.braces.eido</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\t*)((\|)(?:\w+|[\\'\[\]\(\)~!@#$%^&amp;*\./&lt;&gt;?;:"\{\}\|\-=_+]\w*|,))</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.function.eido</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!^\1\t)(?=[ \t]*\S)</string>
			<key>name</key>
			<string>meta.string.unquoted.block.raw.eido</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key><string>string.unquoted.raw.block.eido</string>
					<key>match</key><string>^.+</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(`+).*?\1</string>
			<key>name</key>
			<string>string.quoted.code.eido</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*+|~+</string>
			<key>name</key>
			<string>keyword.operator.eido</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.eido</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\)(?:\w+|[\\'\[\]\(\)~!@#$%^&amp;*\./&lt;&gt;?;:"\{\}\|\-=_+]\w*|,)</string>
			<key>name</key>
			<string>keyword.function.eido</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.eido</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t*(::?)(?:\w+|[\\'\[\]\(\)~!@#$%^&amp;*\./&lt;&gt;?;:"\{\}\|\-=_+]\w*|,)</string>
			<key>name</key>
			<string>keyword.function.eido</string>
		</dict>
		<dict>
		    <key>match</key>
		    <string>[$£¥‘“〈《「『【〔＄（［｛｢￡￥]*[&#x3000;-&#x9fff;][!%,.:;?¢°’”‰′″℃、。​々〉》」』】〕ぁぃぅぇぉっゃゅょゎ゛゜ゝゞァィゥェォッャュョヮヵヶゕゖㇰㇱㇲㇳㇴㇵㇶㇷㇸㇹㇺㇻㇼㇽㇾㇿ・ーヽヾ！％），．：；？］｝​｡｣､･ｧｨｩｪｫｬｭｮｯｰﾞﾟ￠]*</string>
		    <key>name</key>
		    <string>meta.cjkword</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.eido</string>
	<key>uuid</key>
	<string>3277227e-5677-4aae-8a1c-b7f7d39e0b0c</string>
</dict>
</plist>
